# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Word.destroy_all
Word.create([
  {
    word: "house",
    definition:[{"text":"A structure serving as a dwelling for one or more persons, especially for a family."},{"text":"A household or family."},{"text":"Something, such as a burrow or shell, that serves as a shelter or habitation for a wild animal."},{"text":"A dwelling for a group of people, such as students or members of a religious community, who live together as a unit:  a sorority house. "},{"text":"A building that functions as the primary shelter or location of something:  a carriage house; the lion house at the zoo. "},{"text":"A facility, such as a theater or restaurant, that provides entertainment or food for the public:  a movie house; the specialty of the house. "},{"text":"The audience or patrons of such an establishment:  a full house. "},{"text":"A commercial firm:  a brokerage house. "},{"text":"A publishing company:  a house that specializes in cookbooks. "},{"text":"A gambling casino."}],
    example:{"examples":[{"text":"House prices could be supported by purchase of housing -- house buyer of last resort."},{"text":"You'll see, we'll have a Marxist in the White House now, and Marxists running the house and senate."},{"text":"Last weekend, I set about to decorate my perfect tree. in my scaled down, dream house, for my very first christmas ~in the blue and white house~ celebrating my \"this is as good as it gets\" reality."},{"text":"My dad continued working at the post office and we moved to a house on e 38th court before I turned one… my house… just a little bit of background info…"},{"text":"He actually was so upset at me that he drove us back to his house, got out of my truck, and walked inside the house…"}]},
    relatedwords:[{"relationshipType":"synonym","words":["abode","residence","dwelling","tenement","household","tribe","inn","hotel","audience","harbor"]}]
  },
  {
    word: "brace",
    definition: {"definitions":[{"text":"A device that holds or fastens two or more parts together or in place; a clamp."},{"text":"A device, such as a supporting beam in a building or a connecting wire or rope, that steadies or holds something else erect."},{"text":"Chiefly British   Suspenders."},{"text":"An orthopedic appliance used to support, align, or hold a bodily part in the correct position."},{"text":"A dental appliance constructed of bands and wires that is fixed to the teeth to correct irregular alignment. Often used in the plural."},{"text":"An extremely stiff, erect posture."},{"text":"A cause or source of renewed physical or spiritual vigor."},{"text":"A protective pad strapped to the bow arm of an archer."},{"text":"Nautical   A rope by which a yard is swung and secured on a square-rigged ship."},{"text":"A cranklike handle with an adjustable aperture at one end for securing and turning a bit."}]},
    example:{"examples":[{"text":"The term brace, which imports a pair, was employed."},{"text":"Going back to a brace is a step backward; digression."},{"text":"But the point I refer to is this: the old instrument, the trepan, had a handle like a wimble, what we call a brace or bit-stock."},{"text":"Hanging on the brace was a large copper kettle, its sides blackened with soot."},{"text":"Second course, what they're calling a brace of American birds, and the third and final course, apple sponge cake."}]},
    relatedwords:["relatedwordsWords":[ {"relationshipType":"synonym","words":["tension","bitstock","pair","couple","suspenders","harness","vantbrace","tighten","strain","strengthen"]}]]
  },
  {
    word: "water",
    definition: {"definitions":[{"text":"A clear, colorless, odorless, and tasteless liquid, H2O, essential for most plant and animal life and the most widely used of all solvents. Freezing point 0°C (32°F); boiling point 100°C (212°F); specific gravity (4°C) 1.0000; weight per gallon (15°C) 8.338 pounds (3.782 kilograms)."},{"text":"Any of various forms of water:  waste water. "},{"text":"Naturally occurring mineral water, as at a spa. Often used in the plural."},{"text":"A body of water such as a sea, lake, river, or stream."},{"text":"A particular stretch of sea or ocean, especially that of a state or country:  escorted out of British waters. "},{"text":"A supply of water:  had to turn off the water while repairing the broken drain. "},{"text":"A water supply system."},{"text":"Any of the fluids normally secreted from the body, such as urine, perspiration, tears, or saliva."},{"text":"A fluid present in a body part in abnormal quantities as a result of injury or disease:  water on the knee. "},{"text":"The fluid surrounding a fetus in the uterus; amniotic fluid."}]},
    example: {"examples":[{"text":"Just wanted to confirm: Place the bowl over a saucepan of simmering water, making sure that bottom of bowl *does not touch the water*."},{"text":"In context 2 and context 3, Oscar's ˜water™-thoughts are about water, i.e. H2O, while in context 1 they are about XYZ."},{"text":"And at a certain period in the investigation of the underlying nature of water, it would have been correct to say that water might not contain hydrogen, if ˜water™ picked out something different than it actually does."},{"text":"The acceptance of rooftop water harvesting as a suitable system may depend on the users’ views on the water’ s taste."},{"text":"Note: These drawings can also be made for different water collection and transport methods (“water options”)."}]},
    relatedwords: [{"relationshipType":"synonym","words":["moisten","irrigate","extend","dilute","weaken","aquatic","hydraulic","calender","moiré","moire"]}]
  },
  {
    word: "check",
    definition: {"definitions":[{"text":"An action or influence that stops motion or expression; a restraint:  Heavy rains were a check on the army's advance. "},{"text":"The condition of being stopped or held back; restraint:  kept my temper in check; holding agricultural pests in check with sprays. "},{"text":"An abrupt stop in forward movement or progress; a halt."},{"text":"The act or an instance of inspecting or testing, as for accuracy or quality; examination:  the careful check of each unit before sale; gave the car an oil check. "},{"text":"A standard for inspecting or evaluating; a test."},{"text":"A check mark."},{"text":"A ticket or slip of identification:  a baggage check. "},{"text":"A bill at a restaurant or bar."},{"text":"Games   A chip or counter used in gambling."},{"text":"A written order to a bank to pay the amount specified from funds on deposit; a draft."}]},
    example: {"examples":[{"text":"Fixed: Potential problem where ImgBurn might check for updates more often than it should do because the \\'last update check\\ 'value isn\\'t parsed correctly due to regional settings."},{"text":"\"In\": \"Out\" tooltip % check% if check = out; I dunno how redraw with DllCall ..."},{"text":"The only way we can keep Koch in check is to keep exposing these fake grassroots organizations."},{"text":"Yes | No | Report from stephensfamily@ ... wrote 9 weeks 3 days ago keeping those dogs in check is always a good deal."},{"text":"Leaders Without a Title check their egos at the front door every morning before they walk into work."}]},
    relatedwords: [{"relationshipType":"synonym","words":["setback","obstruction","repulse","reproof","counterbalance","hindrance","censure","draft","interruption","tally"]}]
  },
  { 
    word: "issue",
    definition: {"definitions":[{"text":"The act or an instance of flowing, passing, or giving out."},{"text":"The act of circulating, distributing, or publishing by an office or official group:  government issue of new bonds. "},{"text":"Something produced, published, or offered, as:"},{"text":"An item or set of items, as stamps or coins, made available at one time by an office or bureau."},{"text":"A single copy of a periodical:  the May issue of the magazine. "},{"text":"A distinct set of copies of an edition of a book distinguished from others of that edition by variations in the printed matter."},{"text":"A final result or conclusion, as a solution to a problem."},{"text":"Proceeds from estates or fines."},{"text":"Something proceeding from a specified source:  suspicions that were the issue of a deranged mind. "},{"text":"Offspring; progeny:  died without issue. "}]},
    example: {"examples":[{"text":"I do not see how it's a racial issue: it's a people issue, one of the many many Stupid Human Tricks available to us all."},{"text":"\"The MUI must issue a fatwa * on the issue* if there is a request from an institution or individual."},{"text":"Cyprus apart, the main issue is Europe's own economic travail."},{"text":"\"The main issue is to ... come up with a credible program.\""},{"text":"But the main issue is that, meals assembled from lists of dishes on menus, have by their nature, a logic."}]},
    relatedwords: [{"relationshipType":"synonym","words":["egress","delivery","issuance","progeny","upshot","conclusion","event","test","trial","spring"]}],
    },
    {
    word: "prick",
    definition: {"definitions":[{"text":"The act of piercing or pricking."},{"text":"The sensation of being pierced or pricked."},{"text":"A persistent or sharply painful feeling of sorrow or remorse."},{"text":"A small, sharp, local pain, such as that made by a needle or bee sting."},{"text":"A small mark or puncture made by a pointed object."},{"text":"A pointed object, such as an ice pick, goad, or thorn."},{"text":"A hare's track or footprint."},{"text":"Vulgar Slang   A penis."},{"text":"Vulgar Slang   A person regarded as highly unpleasant, especially a male."},{"text":"To puncture lightly."}]},
    example: {"examples":[{"text":"I don't think this prick is a true Georgian if he didn't have a gun in his home."},{"text":"Ms. Bush thinks its OK to use the word \"prick\" in a email, imagine if a man used the word \"pussy.\""},{"text":"Bush, who started out as a bookkeeper and was eventually promoted to regional sales manager but claims she was passed over for more senior positions because of her gender, said she later was fired for using the word \"prick\" in an e-mail."},{"text":"I thought only football managers engaged in prick-waving?"},{"text":"The word prick-song occurs not only in all the musical books, but in the literature of the time, and in"}]},
    relatedwords: [{"relationshipType":"synonym","words":["goad","point","skewer","puncture","degree","pitch","choose","mark","spur","incite"]}],
    },
    {
    word: "stamp",
    definition: {"definitions":[{"text":"To bring down (the foot) forcibly."},{"text":"To bring the foot down onto (an object or surface) forcibly."},{"text":"To extinguish or destroy by or as if by trampling underfoot:  stamped the rebellion; stamp out a fire. "},{"text":"To crush or grind with a heavy instrument:  stamp ore. "},{"text":"To form or cut out by application of a mold, form, or die."},{"text":"To imprint or impress with a mark, design, or seal."},{"text":"To impress forcibly or permanently."},{"text":"To affix an adhesive stamp to."},{"text":"To identify, characterize, or reveal:  stamped her a traitor to the cause. "},{"text":"To thrust the foot forcibly downward."}]},
    example: {"examples":[{"text":"DeleteCommand = \"DELETE FROM Relations WHERE src = @src AND dest = @dest AND stamp = @stamp\" asp: ControlParameter ControlID ="},{"text":"It took more than ten visits to OIT, 5 different signatures, plus the signature and a very official stamp from the Lehrstuhl."},{"text":"Foremost, the time/date stamp is completely unreadable."},{"text":"The biggest buzzkill for the Palin stamp, however, is likely the failure of her name to count, or maybe even to hurt, in some key races that were both more risky for her to get involved in, as well as more important for the GOP to capture."},{"text":"When it reaches the Cuernavaca post office, a date and time stamp is put on the back of the envelope."}]},
    relatedwords: [{"relationshipType":"synonym","words":["crush","pulverize","imprint","mint","coin","strike","beat","impression","cut","plate"]}],
     },
     {
    word: "grain",
    definition: {"definitions":[{"text":"A small, dry, one-seeded fruit of a cereal grass, having the fruit and the seed walls united:  a single grain of wheat; gleaned the grains from the ground one at a time.  Also called caryopsis."},{"text":"The fruits of cereal grasses especially after having been harvested, considered as a group:  The grain was stored in a silo. "},{"text":"A cereal grass:  Wheat is a grain grown in Kansas. "},{"text":"Cereal grasses considered as a group:  Grain is grown along the river. "},{"text":"A relatively small discrete particulate or crystalline mass:  a grain of sand. "},{"text":"A small amount or the smallest amount possible:  hasn't a grain of sense. "},{"text":"Aerospace   A mass of solid propellant."},{"text":"A unit of weight in the U.S. Customary System, an avoirdupois unit equal to 0.002285 ounce (0.065 gram). See Table at measurement."},{"text":"The arrangement, direction, or pattern of the fibrous tissue in wood."},{"text":"The side of a hide or piece of leather from which the hair or fur has been removed."}]},
    example: {"examples":[{"text":"We are not happy with whole grain machine-made bread, and I have never known anyone happy with whole grain machine-made bread, no matter what King Arthur Flour may say."},{"text":"They severally represented a function, a moment in the life of man or of the universe; thus Naprît was identified with the ripe ear, or the grain of wheat; [*] * The word naprît means grain, the grain of wheat."},{"text":"Livelier than ... the grain Of Sarra, \"etc. And as these were fast or durable colours we have such phrases as 'to dye in grain,'"},{"text":"The amount of revenue collected in grain is omitted, as being of less interest: –"},{"text":"UPDATE: Recall that when cooking, oftentimes cutting against the grain is the right thing to do."}]},
    relatedwords: [{"relationshipType":"synonym","words":["texture","temper","inclination","granulate","kermes","cochineal"]}],
    },
    {
    word: "rough",
    definition: {"definitions":[{"text":"Having a surface marked by irregularities, protuberances, or ridges; not smooth."},{"text":"Coarse or shaggy to the touch:  a rough scratchy blanket. "},{"text":"Difficult to travel over or through:  the rough terrain of the highlands. "},{"text":"Characterized by violent motion; turbulent:  rough waters. "},{"text":"Difficult to endure or live through, especially because of harsh or inclement weather:  a rough winter. "},{"text":"Unpleasant or difficult:  had a rough time during the exam. "},{"text":"Boisterous, unruly, uncouth, or rowdy:  ran with a rough crowd. "},{"text":"Lacking polish or finesse:  rough manners. "},{"text":"Characterized by carelessness or force, as in manipulating:  broke the crystal through rough handling. "},{"text":"Harsh to the ear:  a rough raspy sound. "}]},
    example: {"examples":[{"text":"Of course my rough drafts aren't going to be as good as something I pick up off the shelf, that's why they're called rough."},{"text":"She did not care for what she called my rough ways."},{"text":"Chambers served 15 years in prison for the 1986 killing of Jennifer Levin, a death he claims happened accidentally during what he called rough sex."},{"text":"The prosecutor described in her opening statement that Joseph Smith had what she called rough sex with this little girl."},{"text":"'' The problem with Bermuda rough is the ball sinks in it, '' said Jones."}]},
    relatedwords: [{"relationshipType":"antonym","words":["smooth"]},{"relationshipType":"synonym","words":["uneven","uncut","boisterous","high","shaggy","ragged","disordered","harsh","rude","uncivil"]}],
    },
    {
    word: "wheel",
    definition: {"definitions":[{"text":"A solid disk or a rigid circular ring connected by spokes to a hub, designed to turn around an axle passed through the center."},{"text":"Something resembling such a disk or ring in appearance or movement or having a wheel as its principal part or characteristic, as:"},{"text":"The steering device on a vehicle."},{"text":"A potter's wheel."},{"text":"A water wheel."},{"text":"A spinning wheel."},{"text":"Games   A device used in roulette and other games of chance."},{"text":"A firework that rotates while burning."},{"text":"Informal   A bicycle."},{"text":"An instrument to which a victim was bound for torture during the Middle Ages."}]},
    example: {"examples":[{"text":"Often a wheel, sometimes a cart-wheel or even a spinning-wheel, formed part of the mechanism; in Aberdeenshire it was called “the muckle wheel”; in the island of Mull the wheel was turned from east to west over nine spindles of oak-wood."},{"text":"Heah come a wheel -- two wheels -- three wheels; fetch one mo '; heah, a odd wheel; de train's a-saggin' down lop-sided fur one mo 'wheel!"},{"text":"The wheel of Fortune is not the wheel of a housewife."},{"text":"There is no necessity of our seeing one another in the business, but I do want to put my shoulder to the wheel -- wheel of Fortune, eh? ha, ha! \"and he rubbed his large hands gleefully till they fairly glowed."},{"text":"The term wheel is used because the Buddha's teachings explain the cycle or circle of existence."}]},
    relatedwords: [{"relationshipType":"synonym","words":["velocipede","disk","orb","rotation","compass","revolve","rotate","gyrate","turn","roll"]}],
    },
    {
    word: "tender",
    definition: {"definitions":[{"text":"Easily crushed or bruised; fragile:  a tender petal. "},{"text":"Easily chewed or cut:  tender beef. "},{"text":"Young and vulnerable:  of tender age. "},{"text":"Frail; delicate."},{"text":"Sensitive to frost or severe cold; not hardy:  tender green shoots. "},{"text":"Easily hurt; sensitive:  tender skin. "},{"text":"Painful; sore:  a tender tooth. "},{"text":"Considerate and protective; solicitous:  a tender mother; his tender concern. "},{"text":"Characterized by or expressing gentle emotions; loving:  a tender glance; a tender ballad. "},{"text":"Given to sympathy or sentimentality; soft:  a tender heart. "}]},
    example: {"examples":[{"text":"The word that this singer uses is one that only appears in this place, and if we regard its etymology, there lies in it a very tender and beautiful expression of the warmth of the divine love, for it is probably connected with words in an allied language which mean the bosom and a tender embrace, and so the picture that we have is of that great divine Lover folding 'the people' to His heart, as a mother might her child, and cherishing them in His bosom."},{"text":"Seared or grilled, as they are here, the lamb cubes become what he called \"tender little morsels.\""},{"text":"` ` This craven, '' he thought, ` ` will lose the day in pure faintness and cowardice of heart, which he calls tender conscience."},{"text":"They are what we call tender, you see, and in November they must be bent down close to the ground and covered with earth, or else every cane would be dead from frost by spring."},{"text":"I felt my mother’s hand on my shoulder and saw her face reflected in the window, her expression tender as she looked at the baby in my arms, her eyes shining as she kissed me and then the baby’s forehead; her secret face, the one she’s only ever shown to me."}]},
    relatedwords: [{"relationshipType":"antonym","words":["demand"]},{"relationshipType":"synonym","words":["nurse","pitiful","delicate","humane","compassionate","merciful","kind","sensitive","soft","effeminate"]}],
    },
    {
    word: "cross",
    definition: {"definitions":[{"text":"An upright post with a transverse piece near the top, on which condemned persons were executed in ancient times."},{"text":"The upright post with a transverse piece upon which Jesus was crucified."},{"text":"A crucifix."},{"text":"Any of various modifications of the cross design, such as a Latin cross or Maltese cross."},{"text":"A medal, emblem, or insignia in the form of a cross."},{"text":"The Christian religion; Christianity."},{"text":"In Christianity, a sign made by tracing the outline of a cross with the right hand upon the forehead and chest as a devotional act."},{"text":"A trial, affliction, or frustration. See Synonyms at burden1."},{"text":"A mark or pattern formed by the intersection of two lines, especially such a mark (X) used as a signature."},{"text":"A movement from one place to another, as on a stage; a crossing."}]},
    example: {"examples":[{"text":"However, I love seeing the simple 'garden spider' / 'cross spider', the one that weaves beautiful webs in my garden and has a white cross pattern on its back."},{"text":"What makes you think anything about the cross dressing in 'cross and single speed MTB is ironic?"},{"text":"If we ask what the question is that the passage overall poses, or what the change is that needs to be taking place over the time of the passage's narration, it is about the move from desolation in the face of the cross (Jesus 'cross and the implicit demand for the disciple to carry the cross also) to confidence that the process is the work of love coming from and leading to the Father."},{"text":"In fact, what came out in cross examination, through Mark Geragos 'cross examination, is that there were at least 243 different locations throughout the bay that were being searched by those divers."},{"text":"It crept onwards towards the station of the cross, but -- it never reached the cross."}]},
    relatedwords: [{"relationshipType":"synonym","words":["trial","disappointment","opposition","misfortune","fretful","peevish","transverse","oblique","intersecting","interrupting"]}],
    },
    {
    word: "color",
    definition: {"definitions":[{"text":"That aspect of things that is caused by differing qualities of the light reflected or emitted by them, definable in terms of the observer or of the light, as:"},{"text":"The appearance of objects or light sources described in terms of the individual's perception of them, involving hue, lightness, and saturation for objects and hue, brightness, and saturation for light sources."},{"text":"The characteristics of light by which the individual is made aware of objects or light sources through the receptors of the eye, described in terms of dominant wavelength, luminance, and purity."},{"text":"A substance, such as a dye, pigment, or paint, that imparts a hue."},{"text":"The general appearance of the skin; complexion."},{"text":"A ruddy complexion."},{"text":"A reddening of the face; a blush."},{"text":"The skin pigmentation of a person not categorized as white."},{"text":"A flag or banner, as of a country or military unit."},{"text":"The salute made during the ceremony of raising or lowering a flag."}]},
    example: {"examples":[{"text":"If the required color extends uniformly over the entire loaf, the bottom and the sides, as well as the top, 2 more is added to the score of the crust for uniformity of color."},{"text":"Depends on form, with More appropriate to objects color as a secondary adjunct. which depend on color for their principal charm."},{"text":"This naturally suggests, not only a record of each separate color sensation, but also a union of these records in series and groups to form a color score, similar to the musical score by which the measured relations of sound are recorded."},{"text":"No slight difference this, when we reflect on the contrarieties of practice ultimately connected with the opposing principles; above all on the eminent one that, as all Van Eyck's color, except the high lights, must have been equivalent to a glaze, while the great body of color in"},{"text":"PixelGetColor, color, % MouseX%, % MouseY% if % color% = 0x000000"}]},
    relatedwords: [{"relationshipType":"synonym","words":["paint","pigment","semblance","excuse","disguise","appearance","kind","species","hide","blush"]}],
    },
    {
    word: "point",
    definition: {"definitions":[{"text":"A sharp or tapered end:  the point of a knife; the point of the antenna. "},{"text":"An object having a sharp or tapered end:  a stone projectile point. "},{"text":"A tapering extension of land projecting into water; a peninsula, cape, or promontory."},{"text":"A mark formed by or as if by a sharp end."},{"text":"A mark or dot used in printing or writing for punctuation, especially a period."},{"text":"A decimal point."},{"text":"Linguistics   A vowel point."},{"text":"One of the protruding marks used in certain methods of writing and printing for the blind."},{"text":"Mathematics   A dimensionless geometric object having no properties except location."},{"text":"Mathematics   An element in a geometrically described set."}]},
    example: {"examples":[{"text":"Shkedy's team uses the Bible as a starting point to see what animals were once in Israel, reading the Scriptures with a conservationists 'point of view."},{"text":"Thom: And back to Chris Hedges 'point, and the larger point of is the planet melting down, are we melting down, and is it because of the way we think?"},{"text":"BROWN: Go ahead, David, but to address this point about whether or not the players have leverage really or, as to James 'point earlier, would the owners actually decide, you know, if this turned into something, like, hey, we don't want to deal with this; who needs the controversy?"},{"text":"\"\" We're trying to tell players that once you go past the point of [impasse], it's difficult to put the yolk back in the egg, '' said the Boston Red Sox's John Harrington, the owners 'point man."},{"text":"I want to just make one point about Paul's point -- James 'point, excuse me, and that it's not just Democrats that are -- excuse me, Republicans that are fired up this way and making these horrible statements like the one woman and even the gentleman who shouted \"terrorist,\" listen, let me show you some of the e-mails that I get from the fired up left and Obama supporters."}]},
    relatedwords: [{"relationshipType":"synonym","words":["appoint","prick","moment","instant","step","stage","characteristic","peculiarity","item","detail"]}],
    },
    {
    word: "sweep",
    definition: {"definitions":[{"text":"To clean or clear, as of dirt, with or as if with a broom or brush:  sweep a chimney. "},{"text":"To clear away with or as if with a broom or brush:  swept snow from the steps. "},{"text":"To clear (a path or space) with or as if with a broom."},{"text":"To search thoroughly:  The counselors swept the dormitory during the fire drill. "},{"text":"Electronics   To search for and remove (eavesdropping devices) from a place:  swept the room for bugs. "},{"text":"To touch or brush lightly, as with a trailing garment:  willow branches sweeping the ground. "},{"text":"To pass over or through a surface or medium with a continuous movement:  He swept the sponge over the tile. The conductor swept her baton through the air. "},{"text":"To clear, drive, or convey with relentless force:  The flood waters swept away everything in their path. "},{"text":"To wipe out at a single stroke. Often used with away:  The incident in effect swept away all her dreams. "},{"text":"To remove or carry off with a swift brushing motion:  swept the cards off the table; swept the child into his arms. "}]},
    example: {"examples":[{"text":"Quiz Karl, get out the broom and lift up the rug * sweep, sweep*"},{"text":"KOPLAN: The term sweep, I'm not quite sure how are they using it."},{"text":"It started about 7: 00 a.m. local time and it's part of what they call a sweep and clean mission."},{"text":"Most impressive in the sweep is the Angels accomplished it by winning the final two games by a run and two without their closer, Troy"},{"text":"\"Against two undefeated pitchers, to get a sweep is a lot more than we expected,\" said Arizona's Mark Grace, noting that his club also handed Pedro Martinez his first loss of the season."}]},
    relatedwords: [{"relationshipType":"synonym","words":["sweeper","slam","rush","stalk","surge","besom","brush"]}],
    },
    {
    word: "drift",
    definition: {"definitions":[{"text":"To be carried along by currents of air or water:  a balloon drifting eastward; as the wreckage drifted toward shore. "},{"text":"To proceed or move unhurriedly and smoothly:  drifting among the party guests. "},{"text":"To move leisurely or sporadically from place to place, especially without purpose or regular employment:  a day laborer, drifting from town to town. "},{"text":"To wander from a set course or point of attention; stray."},{"text":"To vary from or oscillate randomly about a fixed setting, position, or mode of operation."},{"text":"To be piled up in banks or heaps by the force of a current:  snow drifting to five feet. "},{"text":"To cause to be carried in a current:  drifting the logs downstream. "},{"text":"To pile up in banks or heaps:  Wind drifted the loose straw against the barn. "},{"text":"Western U.S.   To drive (livestock) slowly or far afield, especially for grazing."},{"text":"The act or condition of drifting."}]},
    example: {"examples":[{"text":"A big part of the policy story is what we call \"drift\" - the deliberate failure to update policies to reflect changing economic realities despite viable and popular alternatives due to the pressure of those benefiting from such calculated inaction."},{"text":"The old and discredited neo-conservatives like Rumsfeld, Wolfowitz, Bolton and Jeb Bush sought to link domestic controversies surrounding the Clinton administration to what they described as a drift in American foreign and defense policy."},{"text":"I have dived myself there in the Netherland Antilles, and we did what you call drift diving, where it carries you along, the water does, because there ` s a very heavy current."},{"text":"They profess to see the approaching extinction of the American democracy in what they call the drift towards centralization."},{"text":"We're happy to say when we did that we showed through what they call drift ftr very sophisticated ftr analysis and quantitative X-ray diffraction that we truly had hit the home run because all of the activating chemicals down to parts per trillion."}]},
    relatedwords:[{"relationshipType":"synonym","words":["driving","setting","intention","aim","broach","driftway","prospect","movement","driftage"]}],
    },
    {
    word: "spread",
    definition: {"definitions":[{"text":"To open to a fuller extent or width; stretch:  spread out the tablecloth; a bird spreading its wings. "},{"text":"To make wider the gap between; move farther apart:  spread her fingers. "},{"text":"To distribute over a surface in a layer:  spread varnish on the steps. "},{"text":"To cover with a layer:  spread a cracker with butter. "},{"text":"To distribute widely:  The tornado spread destruction. "},{"text":"To make a wide or extensive arrangement of:  We spread the bicycle parts out on the floor. "},{"text":"To exhibit or display the full extent of:  the scene that was spread before us. "},{"text":"To cause to become widely seen or known; scatter or disseminate:  spread the news; spread the beam of the flashlight. "},{"text":"To prepare (a table) for eating; set."},{"text":"To arrange (food or a meal) on a table."}]},
    example: {"examples":[{"text":"As the Grateful Dead toured the globe through the '70s and '80s, playing hundreds of shows a year - the term spread though the Dead underground."},{"text":"\"The word spread pretty quickly around here: They had service and nice planes,\" said Gary Adams , senior vice president of Anchor/Russell Capital Advisors LLC, a Boston money-management firm."},{"text":"The word spread quickly around town about Till's alleged actions."},{"text":"When the blog Chicks in the Huddle broke the news, the word spread like wildfire."},{"text":"The word spread beyond the social networking on Joga.com through many non-Nike websites, as soccer amateurs sought to co-opt others."}]},
    relatedwords:[{"relationshipType":"synonym","words":["scatter","dispense","distribute","propagate","disseminate","diffuse","publish","circulate","disperse","divulge"]}],
    },
    {
    word: "clear",
    definition: {"definitions":[{"text":"Free from clouds, mist, or haze:  a clear day. "},{"text":"Not obscured or darkened; bright:  clear daylight; a clear yellow. "},{"text":"Easily seen through; transparent:  clear water. "},{"text":"Free from flaw, blemish, or impurity:  a clear, perfect diamond; a clear record with the police. "},{"text":"Free from impediment, obstruction, or hindrance; open:  a clear view; a clear path to victory. "},{"text":"Plain or evident to the mind; unmistakable:  a clear case of cheating. "},{"text":"Easily perceptible to the eye or ear; distinct."},{"text":"Discerning or perceiving easily; keen:  a clear mind. "},{"text":"Free from doubt or confusion; certain."},{"text":"Free from qualification or limitation; absolute:  a clear winner. "}]},
    example: {"examples":[{"text":"It is connected with the former of them by the recurrence of the same word, which in the first petition was rendered 'cleanse' -- or, more accurately, 'clear' -- and in this final clause is to be rendered accurately, 'I shall be clear from the great transgression.'"},{"text":"clear, or as clear a one as will pass muster with the government and with the preconceptions of the people themselves."},{"text":"I wish to explain -- to make clear to you -- clear."}]},
    relatedwords:[{"relationshipType":"antonym","words":["cloudy","obscure","thick"]},{"relationshipType":"synonym","words":["visible","manifest","distinct","pure","obvious","evident","apparent","pellucid","perspicuous","unmixed"]}],
    },
    {
    word: "drive",
    definition: {"definitions":[{"text":"To push, propel, or press onward forcibly; urge forward:  drove the horses into the corral. "},{"text":"To repulse or put to flight by force or influence:  drove the attackers away; drove out any thought of failure. "},{"text":"To guide, control, or direct (a vehicle)."},{"text":"To convey or transport in a vehicle:  drove the children to school. "},{"text":"To traverse in a vehicle:  drive the freeways to work. "},{"text":"To supply the motive force or power to and cause to function:  Steam drives the engine. "},{"text":"To cause or sustain, as if by supplying force or power: \"The current merger mania is apparently driven by an urge . . . to reduce risk or to exploit opportunities in a very rapidly changing business environment”  ( Peter Passell). "},{"text":"To compel or force to work, often excessively: \"Every serious dancer is driven by notions of perfection—perfect expressiveness, perfect technique”  ( Susan Sontag). "},{"text":"To force into or from a particular act or state:  Indecision drives me crazy. "},{"text":"To force to go through or penetrate:  drove the stake into the ground. "}]},
    example: {"examples":[{"text":"They ask for the image to be on a flash drive, then use the drive as the decoration."},{"text":"Cone drive: Another old system that is often used in factories is the “cone drive” system."},{"text":"If they make it hard for people them to get drivers licenses -- the primary purpose of which is to say somebody knows how to drive* -- then they won't drive legally."},{"text":"Hopefully the main drive is fine and can be transferred to a new computer eventually for accessing it."},{"text":"Central to the latest McCain drive is an attempt to use against Mr. Obama the huge crowds and excitement he has drawn, including on his foreign trip last week, by promoting a view of him as more interested in attention and adulation than in solving the problems facing American families."}]},
    relatedwords: [{"relationshipType":"synonym","words":["force","constrain","conduct","prosecute","strive","driven","ride","driveway","excavation","drift"]}],
    },
    {
    word: "white",
    definition: {"definitions":[{"text":"The achromatic color of maximum lightness; the color of objects that reflect nearly all light of all visible wavelengths; the complement or antagonist of black, the other extreme of the neutral gray series. Although typically a response to maximum stimulation of the retina, the perception of white appears always to depend on contrast."},{"text":"The white or nearly white part, as:"},{"text":"The albumen of an egg."},{"text":"The white part of an eyeball."},{"text":"A blank unprinted area, as of an advertisement."},{"text":"One that is white or nearly white, as:"},{"text":"White trousers or a white outfit of a special nature:  tennis whites. "},{"text":"The white dress uniform of the U.S. Navy or Coast Guard."},{"text":"A white wine."},{"text":"A white pigment."}]},
    example: {"examples":[{"text":"When people squint and say, Scott, you are a white guy, I peel off a shoe and sock and show them what my untanned skin looks like; \"Oh, white guy.\""},{"text":"If the term ˜white™ stands for its suppositum, it refers to a thing that is white or to ˜that which is white™, but if it stands for the quality or form, it refers to the whiteness inhering in that which is white, rather than to the thing in which it inheres."},{"text":"Hence white horse, the extension of ˜white horse™, is not the same as (identical to) horse, the extension of ˜horse™."},{"text":"A denominative term such as ˜white™ signifies by imposition a substance that is white, but it signifies by representation the whiteness inhering in the substance."},{"text":"His most famous line, “A white horse is not a horse, ” deals with the important distinction between “horse, ” “white, ” and “white horse."}]},
    relatedwords: [{"relationshipType":"antonym","words":["black"]},{"relationshipType":"synonym","words":["pale","pallid","innocent","pure","hoary","fortunate","happy","favorable","favorite","darling"]}],
    }
])
